version: '3.2'

services:
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.backend
    restart: "unless-stopped"
    environment: 
      - PORT=${BACKEND_PORT}
      - SQLITE_DB={BACKEND_SQLITE_DB_PATH}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - HASH_SALT_ROUNDS=${BACKEND_HASH_SALT_ROUNDS}
      - JWT_SECRET=${BACKEND_JWT_SECRET}
    networks: 
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.alter_agent_backend.rule=Host(`${BACKEND_DOMAIN}`)
      - traefik.http.routers.alter_agent_backend.entrypoints=websecure
      - traefik.http.routers.alter_agent_backend.tls=true
      - traefik.http.routers.alter_agent_backend.tls.certresolver=le
      - traefik.http.services.alter_agent_backend.loadbalancer.server.port=3000
  frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.frontend
    restart: "unless-stopped"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.alter_agent.rule=Host(`${FRONTEND_DOMAIN}`)
      - traefik.http.routers.alter_agent.entrypoints=websecure
      - traefik.http.routers.alter_agent.tls=true
      - traefik.http.routers.alter_agent.tls.certresolver=le

networks:
  proxy:
    external: true
